<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.kVIfFyN' shared service.

return $this->privates['.service_locator.kVIfFyN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'countyRepository' => ['privates', 'App\\Repository\\CountyRepository', 'getCountyRepositoryService.php', true],
], [
    'countyRepository' => 'App\\Repository\\CountyRepository',
]);
