<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Gt71.n5' shared service.

return $this->privates['.service_locator.Gt71.n5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'county' => ['privates', '.errored..service_locator.Gt71.n5.App\\Entity\\County', NULL, 'Cannot autowire service ".service_locator.Gt71.n5": it references class "App\\Entity\\County" but no such service exists.'],
], [
    'county' => 'App\\Entity\\County',
]);
