<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.YsarIuU' shared service.

return $this->privates['.service_locator.YsarIuU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'state' => ['privates', '.errored..service_locator.YsarIuU.App\\Entity\\State', NULL, 'Cannot autowire service ".service_locator.YsarIuU": it references class "App\\Entity\\State" but no such service exists.'],
], [
    'state' => 'App\\Entity\\State',
]);
