<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXGCQVlJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXGCQVlJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXGCQVlJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXGCQVlJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXGCQVlJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XGCQVlJ',
    'container.build_id' => '309e5bcd',
    'container.build_time' => 1568919101,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXGCQVlJ');
